### ISSUE TITLE
List to Map 实现类似矩阵的逻辑

### ISSUE THREAD

**Issue by ananbeike** [venusdrogon/feilong-core#270]
场景描述
目标数据为特殊的导航list对象
![image](https://cloud.githubusercontent.com/assets/11962675/17848203/b4904c44-6884-11e6-9247-66be022f4e57.png)
需要转换为以导航名称的首字母分组并排序的map，对应的value也需要按照导航的名词排序
![image](https://cloud.githubusercontent.com/assets/11962675/17848277/1b1c95da-6885-11e6-8adc-73bd94da03e3.png)

**Comment by venusdrogon** [comment]
这个需求还是很有意思的

**Comment by venusdrogon** [comment]
对于 结果map,key的顺序
可以调用 SortUtil 相关排序方法

对于 结果map,value的顺序
建议 先将 list 排序完 (可能按照 数量, 可能按照字母) 然后再调用
