### ISSUE TITLE
json format 需要支持修改key的名字

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-core#505]
json format 需要支持修改key的名字

minglei  说, 我们的java 属性是标准的属性名字, 比如name
但是和第三方对接的时候, 对方的文档要求是 Name, 首字母需要大写的

所以需要增加这么一个功能

## 背景

我们这边的代码 

```JAVA

public class CrmAddpointCommand implements Serializable{

    /** 用户编码 */
    private String openId;

    /** 渠道：Tmall - 天猫 JD - 京东 */
    private String consumptionChannel;

    /** 淘宝/京东买家账号 */
    private String buyerId;

    /** 电商订单编号 */
    private String orderCode;

  // setter getter

```

符合标准的java 代码规范

如果直接使用 com.feilong.tools.jsonlib.JsonUtil.format(Object)

```JAVA

    @Test
    public void testJsonTest(){
        CrmAddpointCommand crmAddpointCommand = new CrmAddpointCommand();

        crmAddpointCommand.setBuyerId("123456");
        crmAddpointCommand.setConsumptionChannel("feilongstore");
        crmAddpointCommand.setOpenId("feilong888888ky");
        crmAddpointCommand.setOrderCode("fl123456");

        LOGGER.debug(JsonUtil.format(crmAddpointCommand));
    }

```

输出结果

```
 {
        "orderCode": "fl123456",
        "buyerId": "123456",
        "consumptionChannel": "feilongstore",
        "openId": "feilong888888ky"
    }
```

输出出来的属性大小写和 crmAddpointCommand 对象里面字段的大小写相同

但是 对方接口要求

![image](https://cloud.githubusercontent.com/assets/3479472/19713507/434572a8-9b79-11e6-987a-07e572df5bf9.png)

要求 首字符要大写

**Comment by shade41-code** [comment]
JsonConfig jsonConfig = new JsonConfig();

        for (Class<?> class1 : classList){
            PropertyNameProcessor propertyNameProcessor = new PropertyNameProcessor(){
                @Override
                public String processPropertyName(Class target,String fieldName){
                    return fieldName.substring(0, 1).toUpperCase() + fieldName.substring(1);
                }
            };
            jsonConfig.registerJsonPropertyNameProcessor(class1, propertyNameProcessor);
        }

        PropertyFilter propertyFilter = new PropertyFilter(){
            @Override
            public boolean apply(Object arg0,String arg1,Object arg2){
                return Validator.isNullOrEmpty(arg2);
            }
        };

        jsonConfig.setCycleDetectionStrategy(CycleDetectionStrategy.LENIENT);
        jsonConfig.setIgnoreDefaultExcludes(false);
        jsonConfig.registerJsonValueProcessor(Date.class, new DateJsonValueProcessor(DatePattern.COMMON_DATE_AND_TIME));
        jsonConfig.setAllowNonStringKeys(true);
        jsonConfig.setJsonPropertyFilter(propertyFilter);

        JSONObject.fromObject(obj, jsonConfig);

这段代码就可以将传入的对象每个属性首字母大写，而且属性值为空的属性不进行序列化

**Comment by venusdrogon** [comment]
我可能更期望 这种匹配关系由调用者来配置

**Comment by venusdrogon** [comment]
@shade41-code 首字符大写 可以使用 org.apache.commons.lang3.StringUtils.capitalize(String)

**Comment by venusdrogon** [comment]
做了一版本 

```JAVA

    @Test
    public void testJsonTest(){
        CrmAddpointCommand crmAddpointCommand = new CrmAddpointCommand();

        crmAddpointCommand.setBuyerId("123456");
        crmAddpointCommand.setConsumptionChannel("feilongstore");
        crmAddpointCommand.setOpenId("feilong888888ky");
        crmAddpointCommand.setOrderCode("fl123456");

        JsonFormatConfig jsonFormatConfig = new JsonFormatConfig();

        Map<Class<?>, PropertyNameProcessor> targetClassAndPropertyNameProcessorMap = newHashMap(1);
        targetClassAndPropertyNameProcessorMap.put(CrmAddpointCommand.class, new CapitalizePropertyNameProcessor());

        jsonFormatConfig.setTargetClassAndPropertyNameProcessorMap(targetClassAndPropertyNameProcessorMap);
        LOGGER.debug(JsonUtil.format(crmAddpointCommand, jsonFormatConfig));
    }

```

输出

```JAVA

**Comment by venusdrogon** [comment]
``

**Comment by venusdrogon** [comment]
不过感觉这么写代码量会比较大 

可以参考 com.fasterxml.jackson.databind.SerializationFeature
