### ISSUE TITLE
添加一个日期前后比较的方法

### ISSUE THREAD

**Issue by guaguawa** [venusdrogon/feilong-core#668]
经常有一种业务是，开始时间，1小时后数据过期，需进行类似的判断

虽然可以通过时间差来比较，但感觉不够简单

**Comment by guaguawa** [comment]
public static void main(String[] args) {

        Date startDate = DateUtil.parseDateTime("2017-09-04 11:52:00");

        Date now = DateUtil.parseDateTime("2017-09-04 12:51:00");

        System.out.println(isExpired(startDate, now, 1, DateField.HOUR));
    }


    static boolean isExpired(Date startDate, Date nowDate, Integer timeLength, DateField dateField){

        Date endDate = DateUtil.offsiteDate(startDate, dateField, timeLength);

        return endDate.before(nowDate);

    }

**Comment by venusdrogon** [comment]
这个issue 为什么自己关掉了 ......
