### ISSUE TITLE
能新增一个对两个集合进行比较的方法吗？

### ISSUE THREAD

**Issue by Knight-JNXU** [venusdrogon/feilong-core#685]
比如说我要比较两个 list 中的所有元素是否相同

**Comment by venusdrogon** [comment]
目前没有添加的计划 

但是你可以使用 `commons-collections4`  (feilong-core 已经内置依赖)

`org.apache.commons.collections4.CollectionUtils.isEqualCollection(Collection<?>, Collection<?>) `


方法
