### ISSUE TITLE
new JSONObject有特殊字符时，getStr不原样输出，变为unicode格式

### ISSUE THREAD

**Issue by weidingplus** [venusdrogon/feilong-core#768]
package com;

public class Test {
	public static void main(String[] args) {
		String str = "{\"test\":\"体”、“文\"}";
		cn.hutool.json.JSONObject json = new cn.hutool.json.JSONObject(str);
		System.out.println(json);
	}
}

--------------输出结果
{"test":"体\u201d、\u201c文"}

**Comment by venusdrogon** [comment]
这是 feilong 开源软件 issue ,  hutool 的你需要移步哦 

feilong 使用


com.feilong.json.jsonlib.JsonUtil.toMap(Object)


![image](https://user-images.githubusercontent.com/3479472/55533995-a3f8c580-56e5-11e9-80db-5497f06aebca.png)
