### ISSUE TITLE
根据对象字段去重,不希望改变List顺序

### ISSUE THREAD

**Issue by DazonWu** [venusdrogon/feilong-core#782]
就是我查了一堆数据,然后根据文件名去重,我需要的是总是显示createdAt这个字段最新的数据

List<bean>

id,  path, createdAt
1        a.txt    10:00
2       b.txt    9:00
3       a.txt    11:00
4      c.txt    13:00
5      d.txt    15:00

id,  path, createdAt
1        a.txt    10:00
**2       b.txt    9:00
3       a.txt    11:00
4      c.txt    13:00
5      d.txt    15:00**

**Comment by venusdrogon** [comment]
此时此刻 现有方案 可以

1. com.feilong.core.util.CollectionsUtil.groupOne(Iterable<O>, String)

2. map values

**Comment by venusdrogon** [comment]
com.feilong.core.util.CollectionsUtil.removeDuplicate(Collection<O>, String...) 

since 2.1.0 是你想要的

**Comment by venusdrogon** [comment]
see #808
