### ISSUE TITLE
StrUtil工具类能增加一个isAnyBlank吗

### ISSUE THREAD

**Issue by leilixiang** [venusdrogon/feilong-core#832]
StrUtil工具类能增加一个isAnyBlank吗？这样就可以判断几个参数中是否存在空值，有一个空值就返回true,不然还要一个一个判断
，在自己项目里面新建一个工具类又有点多余，希望作者能增加一下~
/**
     * description: isAnyBlank 判断是否存在空字符串，Hutool未编写<br>
     * version: 1.0 <br>
     * @date: 2021/8/19 0019 上午 10:25 <br>
     * @author: William <br>
     * @param strs   字符串
     * @return java.lang.Boolean
     */
    public static Boolean isAnyBlank(CharSequence... strs){
        //如果为空直接返回true
        if (ArrayUtil.isEmpty(strs)) {
            return true;
        }
        for (CharSequence str : strs) {
            if (StrUtil.isBlank(str)) {
                return true;
            }
        }
        return false;
    }

**Comment by venusdrogon** [comment]
你去 hutools 去提交task 吧
